In [16]:
import pandas as pd
import numpy as np
import math

In [6]:
df1 = pd.DataFrame({'A': ['one', 'two'], 'B': [1, 2]})

df2 = pd.DataFrame({'A': ['one', 'three'], 'C': [3, 4]})

In [7]:
df1

     A  B
0  one  1
1  two  2

In [8]:
df2

       A  C
0    one  3
1  three  4

In [9]:
df1.merge(df2, how='inner', on='A')

     A  B  C
0  one  1  3

In [13]:
df2.merge(df1, how='inner', on='A')

     A  C  B
0  one  3  1

In [18]:
a = math.nan

In [19]:
type(a)

float

In [22]:
s = ['C', 'A', 'B','A'] 
t = [2,3,2,3]

In [24]:
df=pd.DataFrame({'Name':s,  'Value':t})

In [25]:
print(len(df.drop_duplicates()))

3

In [26]:
I=[35,21,10,55]

In [29]:
ser=pd.Series(I, index=['D', 'A', 'B', 'C'])

In [47]:
(ser.sort_index())

pandas.Series

In [45]:
type(test)

str

In [51]:
test[0:]

'C'